version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.0-alpine-latest
    container_name: zabbix-server
    ports:
      - 80:80
    environment:
      - DB_SERVER_HOST=10.60.1.66
      - MYSQL_USER=devteam
      - MYSQL_PASSWORD=Boss@8055  
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - TZ-Asia/Kolkata
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:6.0-alpine-latest
    container_name: zabbix-web
    ports:
      - 8080:8080
    environment:
      - DB_SERVER_HOST=10.60.1.66
      - MYSQL_USER=devteam
      - MYSQL_PASSWORD=Boss@8055  
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - TZ-Asia/Kolkata
    depends_on:
      - zabbix-server
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 8081:3000
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,grafana-mqtt-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana:rw
    depends_on:
      - zabbix-server
  telegraf:
    image: telegraf
    ports:
    - 8186:8186
    volumes:
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ${PWD}/telegraf/logs:/var/log/telegraf
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.6.4
    volumes:
      - ${PWD}/influxDB/data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=METRICS
      - INFLUXDB_USERNAME=devteam
      - INFLUXDB_PASSWORD=Boss@8055
      - DOCKER_INFLUXDB_INIT_MODE=upgrade
      - DOCKER_INFLUXDB_INIT_USERNAME=devteam
      - DOCKER_INFLUXDB_INIT_PASSWORD=Boss@8055
      - DOCKER_INFLUXDB_INIT_ORG=aditya-org
      - DOCKER_INFLUXDB_INIT_BUCKET=aditya-bucket
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ${PWD}/mosquitto/data:/mosquitto/data
      - ${PWD}/mosquitto/logs:/mosquitto/logs
      - ${PWD}/mosquitto/conf:/mosquitto/config
    restart: unless-stopped
volumes:
  grafana-data:
