version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.0-alpine-latest
    container_name: zabbix-server
    ports:
      - 80:80
    environment:
      - DB_SERVER_HOST=10.60.1.66
      - MYSQL_USER=devteam
      - MYSQL_PASSWORD=Boss@8055  
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - TZ-Asia/Kolkata
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:6.0-alpine-latest
    container_name: zabbix-web
    ports:
      - 8080:8080
    environment:
      - DB_SERVER_HOST=10.60.1.66
      - MYSQL_USER=devteam
      - MYSQL_PASSWORD=Boss@8055  
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - TZ-Asia/Kolkata
    depends_on:
      - zabbix-server
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 8081:3000
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,grafana-mqtt-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana:rw
    depends_on:
      - zabbix-server
volumes:
  grafana-data:
